### ISSUE TITLE
Lack of tutorial / documentation

### ISSUE THREAD

**Issue by zuf** [a-jie/Proton#15]
Hello!
Any plans to provide some kind of documentation?

**Comment by a-jie** [comment]
Thank you for your recognition!
Although I will reply to you soon finished, but I still can't guarantee it. Because I'm too busy!

**Comment by Shadowstep33** [comment]
Any update on this? Proton is one of my favorite html5 libraries but I feel like there's a lot im not grasping still

**Comment by a-jie** [comment]
Recently I was porting proton to three.js and unity. I think that would be more practical.

**Comment by tkmoney** [comment]
Does that mean no docs are coming? is this lib being deprecated or abandoned?
