### ISSUE TITLE
Proton emitter - DOM Renderer - particles with ID names‏ 

### ISSUE THREAD

**Issue by Kfhonics** [a-jie/Proton#16]
Hey Im using your proton emitter for the DOM Renderer.

Simple question: How can I emit particles with ID names?

var particle = document.getElementById("particle")
emitter.addInitialize(new Proton.ImageTarget(particle));

It would be amazing if your engine can do so.

Let me know

**Comment by Kfhonics** [comment]
anyone?

**Comment by a-jie** [comment]
I'm sorry I did not see your question.
Proton.ImageTarget need to pass is an Image object. You are correct . Thank you very much
