### ISSUE TITLE
非常需要文档！谢谢！~

### ISSUE THREAD

**Issue by michael829** [a-jie/Proton#17]
您好，同为flash开发者。您的类库看起来不错。希望能够抽空完善下文档。。谢谢。。示例代码只能满足基本的使用。。。

**Comment by ph2-cst** [comment]
+1

**Comment by a-jie** [comment]
sorry，很抱歉刚刚看到，最近真的是非常的忙！ 有时间一定补上文档，请暂时参照demo编写!
