### ISSUE TITLE
please add documentation to your site

### ISSUE THREAD

**Issue by sashastg** [a-jie/Proton#19]
please add documentation to your site.
its hard to use this amazing library without docs.

2) in Proton.js -> function destory has misprint  -- must be renamed to destroy

**Comment by ph2-cst** [comment]
Oh, the second question is so bad..
"destory" is also in [Behaviour.js](https://github.com/a-jie/Proton/blob/master/src/behaviour/Behaviour.js#L112), [Particle.js](https://github.com/a-jie/Proton/blob/master/src/core/Particle.js#L126)
Terrible, in [Proton.js](https://github.com/a-jie/Proton/blob/master/src/core/Proton.js#L125) -> function destory, it will call Emitter.**destory**(), but function name is "**destroy**" in [Emitter.js](https://github.com/a-jie/Proton/blob/master/src/emitter/Emitter.js#L271), although annotation is "destory" .

**Comment by FranDias** [comment]
PR's welcome just put a PR into the gh-pages branch
https://github.com/a-jie/Proton/tree/gh-pages

**Comment by a-jie** [comment]
Thank you very much. I have fixed the problem with destory.
For documentation, I really want to finish now, if I have time.

**Comment by ph2-cst** [comment]
In fact, you can add comments to the examples  if you do not have enough time. quickly and effectively
