### ISSUE TITLE
Random color not working with Pixi.js render

### ISSUE THREAD

**Issue by zachdsawyer** [a-jie/Proton#2]
I'm using Pixi.js,  but I can't get the random color behaviour to work.

http://www.a-jie.cn/proton/example/render/custom/pixijs.html 
Add this,  and it doesn't change the color.  
emitter.addBehaviour(new Proton.Color('random'));

I looked at Color.prototype.applyBehaviour,  it is executing, but it's not showing up in the render.

I love the framework otherwise, great work!

**Comment by okartgame** [comment]
shawnsnyder thanks you very much :)
