### ISSUE TITLE
Emitter size

### ISSUE THREAD

**Issue by OpherV** [a-jie/Proton#20]
I'd like to suggest the ability for an emitter to define a rectangle in which particles are created at random points, rather than a single point

**Comment by OpherV** [comment]
Oh, I've missed PointZone. My bad :)

**Comment by OpherV** [comment]
w

**Comment by OpherV** [comment]
Ahhh I was searching for RectZone

Sorry for the mess :D

**Comment by a-jie** [comment]
Oh, I'm glad you found your need. Good luck with you
