### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by srvrahul** [a-jie/Proton#28]

**Comment by algjoava** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.5
3 info using node@v0.10.37
4 verbose node symlink /usr/bin/node
5 verbose stack Error: missing script: start
5 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:151:19)
5 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:61:5
5 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
5 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
5 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
5 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
5 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20
5 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
5 verbose stack     at fs.js:208:20
5 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:232:16
6 verbose cwd /home/rahul/angular2-quickstart
7 error Linux 3.13.0-92-generic
8 error argv "node" "/usr/bin/npm" "start"
9 error node v0.10.37
10 error npm  v3.10.5
11 error missing script: start
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by JPeer264** [comment]
I think you got a problem with your `package.json` file. This has actually nothing to do with ProtonJS. 

Please check the correct syntax of your `json` file in `/home/r/angular2-quickstart/package.json`.

**Comment by srvrahul** [comment]
rahul@:~$ sudo npm install -g create-react-app
[sudo] password for rahul: 
/usr/rahul/npm-global/bin/create-react-app -> /usr/rahul/npm-global/lib/node_modules/create-react-app/index.js
+ create-react-app@1.3.3
updated 1 package in 18.296s
rahul@:~$ create-react-app hello
create-react-app: command not found
