### ISSUE TITLE
getImageData error after context.drawImage

### ISSUE THREAD

**Issue by tabsun** [a-jie/Proton#37]
In proton we have following code:
getImageData:function(a,b,c){
a.drawImage(b,c.x,c.y);
var d=a.getImageData(c.x,c.y,c.width,c.height);
a.clearRect(c.x,c.y,c.width,c.height);
return d
}

And I get error @ getImageData, if remove the line of drawImage everything is OK.
As I'm not familiar with html and js, could any one give me some advice?
MUCH THANKS !

**Comment by a-jie** [comment]
Please describe your usage scenario, and error message.

**Comment by tabsun** [comment]
Thanks for response. I have found the reason and anyone who encounter this question may look here:
http://www.cnblogs.com/jdksummer/articles/2565998.html
