### ISSUE TITLE
blendFunc and pixi

### ISSUE THREAD

**Issue by horyzont** [a-jie/Proton#41]
Could you please create an example of usage webgl proton renderer and pixi, such as in: example\render\custom but for eg. https://a-jie.github.io/Proton/example/sparks/sun/fireball.html where we have blendFunc.

**Comment by replaysMike** [comment]
I see this was closed - did you ever find a way to do it? I love the library, but most samples don't look good when using Pixi. Webgl renderer does a great job, but that's only suitable if you can overlay another canvas on top of the Pixi canvas.
