### ISSUE TITLE
how to stop the emitter?

### ISSUE THREAD

**Issue by FatSillyBird** [a-jie/Proton#44]
I try to stop the emitter,I use the cancelAnimationFrame,but by this,the picture just freeze.
I'm a fresh in this,I want to stop the next emitter.Pleae help me.

**Comment by ulisinn** [comment]
I'm working on a trivial example with pix.js v4, this seems to work for me:
    (!emitterActive) ? emitter.emit() : emitter.stopEmit();

**Comment by FatSillyBird** [comment]
Thanks for your help,this is useful and solve my problem.
