### ISSUE TITLE
rendering problem

### ISSUE THREAD

**Issue by jackysharpmotion** [a-jie/Proton#48]
Dear A-jie,

How are you? My name is Jacky, I've tried to use your proton.js to add a particle effect into my webpage, it works fine in FireFox, mobile Safari & mobile Chrome, but not sure why there is a problem of my page when rendering in Mac desktop version Safari and Chrome - but your demo page still looks fine under these 2 platforms!

Here is my link:

https://www.sharpmotion.com.hk/
https://www.sharpmotion.com.hk/about

Attached is the screen shot
![screenshot](https://user-images.githubusercontent.com/6543831/33521865-7bfe7c42-d819-11e7-9f02-7766d2365a02.jpg)

Thanks a lot!

Jacky

**Comment by a-jie** [comment]
You can use the following way. First I suggest you upgrade proton to v3.0

```
renderer = new Proton.WebGLRenderer(canvas);
renderer.gl.blendFuncSeparate(renderer.gl.SRC_ALPHA, renderer.gl.ONE, renderer.gl.ONE, renderer.gl.ONE_MINUS_SRC_ALPHA);
proton.addRenderer(renderer);
```

**Comment by jackysharpmotion** [comment]
We’ve found that it seems not the problem of your old or new js version, as we need to set the particle with an alpha transparency, the problem occurs in Mac desktop version Safari and Chrome only, FireFox and mobile Safari/Chrome is fine

however, when we delete the alpha (change back to 100% opacity), it is OK in Mac desktop version Safari and Chrome again.

Best Regards, 




Jacky Cheung
Director | Creative Director | MHKDA BA (Hons)




Direct: (852) 2529 3715
Mobile: (852) 9871 3371

WeChat: jackysharpmotion
Email: jacky@sharpmotion.com.hk

816, 8/F, Topsail Plaza, 11 On Sum Street, Shek Mun, Shatin, Hong Kong
www.sharpmotion.com.hk

**Comment by a-jie** [comment]
Use my following method to try it
```
renderer = new Proton.WebGLRenderer(canvas);
renderer.gl.blendFuncSeparate(renderer.gl.SRC_ALPHA, renderer.gl.ONE, renderer.gl.ONE, renderer.gl.ONE_MINUS_SRC_ALPHA);
proton.addRenderer(renderer);
```

**Comment by jackysharpmotion** [comment]
Dear A-jie,

Thanks a lot!  we’ll try it out and let you know the outcome shortly!!

Best Regards, 




Jacky Cheung
Director | Creative Director | MHKDA BA (Hons)




Direct: (852) 2529 3715
Mobile: (852) 9871 3371

WeChat: jackysharpmotion
Email: jacky@sharpmotion.com.hk

816, 8/F, Topsail Plaza, 11 On Sum Street, Shek Mun, Shatin, Hong Kong
www.sharpmotion.com.hk

**Comment by jackysharpmotion** [comment]
Dear A-jie,

tried the code but the particle effect even wouldn’t show up …. sorry!

Best Regards, 




Jacky Cheung
Director | Creative Director | MHKDA BA (Hons)




Direct: (852) 2529 3715
Mobile: (852) 9871 3371

WeChat: jackysharpmotion
Email: jacky@sharpmotion.com.hk

816, 8/F, Topsail Plaza, 11 On Sum Street, Shek Mun, Shatin, Hong Kong
www.sharpmotion.com.hk

**Comment by a-jie** [comment]
This is the code for proton v3

**Comment by jackysharpmotion** [comment]
Oh yes, v3 is OK now, we’re fine tuning the parameter as the emission seems not as smooth as the old version


Old and existing: www.sharpmotion.com.hk

New testing: www.sharpmotion.com.hk/index3.html

Thanks a lot!

Jacky

**Comment by jackysharpmotion** [comment]
Not sure why the emission is jigging, not smooth, any pararmeter i need to adjust?


Thanks!

**Comment by jackysharpmotion** [comment]
Dear A-jie,

adjusted a parameter and the problem is fixed.

Thanks a lot for your help indeed! coz this bug bother me quite a bit of time, cheers!

Best Regards, 




Jacky Cheung
Director | Creative Director | MHKDA BA (Hons)




Direct: (852) 2529 3715
Mobile: (852) 9871 3371

WeChat: jackysharpmotion
Email: jacky@sharpmotion.com.hk

816, 8/F, Topsail Plaza, 11 On Sum Street, Shek Mun, Shatin, Hong Kong
www.sharpmotion.com.hk
