### ISSUE TITLE
pixi renderer outdated

### ISSUE THREAD

**Issue by ramarro123** [a-jie/Proton#50]
Hi,

pixirenderer should work with pixi4? i am not able to make it work properly, there are a lot of glitch, mask issue, performance problem and so on.

can you confirm that it's supposed to work and i have to dig more on my side?

**Comment by a-jie** [comment]
Proton engine has now been upgraded to V3 version, pixi.js provides more friendly support. More importantly, you can extend the renderer.pool.create function!

**Comment by c-andrews** [comment]
Hi, 
Has Proton been updated for Pixi V5?

**Comment by a-jie** [comment]
V4, v5 should be available. I have these two versions in my demo.
