### ISSUE TITLE
Removing Emitter leaves particles

### ISSUE THREAD

**Issue by jramstedt** [a-jie/Proton#55]
Removing Emitter stops updating emitted particles and they are left on screen.

I expect particles to die normally after emitter is removed.

I have done a workaround that calls Emitter.stop() and waits for max lifetime and then calls Emitter.destroy()

**Comment by mperronc** [comment]
There is a also a method removeAllParticles() on Emitter that sets all its particles "dead" flag to true.
Calling update() after that destroys all the particles properly.

Kinda threw me off as well.

**Comment by jramstedt** [comment]
What I expected was that particles to run their normal course and die. Like for example fade away.
