### ISSUE TITLE
How to use Proton in Vue.js

### ISSUE THREAD

**Issue by SylarXin** [a-jie/Proton#66]
How to use Proton in Vue.js, which file need to config

**Comment by a-jie** [comment]
An example of proton used in react is as follows. I will write some examples of vue in the near future.

[https://stackblitz.com/edit/proton-color](https://stackblitz.com/edit/proton-color)

**Comment by a-jie** [comment]
About proton is used in vue. You can refer to this example
[https://codesandbox.io/s/proton-collision-ball-9mql1?fontsize=14&module=%2Fsrc%2Fcomponents%2FParticles.vue](https://codesandbox.io/s/proton-collision-ball-9mql1?fontsize=14&module=%2Fsrc%2Fcomponents%2FParticles.vue)

**Comment by SylarXin** [comment]
Thanks! It really helps!
